package tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.AssertionsForClassTypes.assertThat;


public class SmokeTests extends TestBase {
    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://sbibankllc.ru/'", () ->
                open("https://sbibankllc.ru/"));

        step("Page title should have text 'Эс-Би-Ай Банк | SBI Bank'", () -> {
            String expectedTitle = "Эс-Би-Ай Банк | SBI Bank";
            String actualTitle = title();

            assertThat(actualTitle).contains(expectedTitle);
        });
    }
}
